/* Platform-neutral long-form reading. Source links immediately follow facts. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./core.cjs'),require('../news/i18n.cjs'),require('../news/core.cjs'));else root.FrontierBriefingRender=factory(root.FrontierBriefing,root.FrontierI18n,root.FrontierData);})(typeof globalThis!=='undefined'?globalThis:this,function(core,i18n,news){
 const escape=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function sourceLink(source,language){const t=i18n.dictionary(language).briefing,label=`${t.sourceTypes[source.type]||t.source}｜${source.name}`,href=core.sourceUrl(source.url);return href?`<a class="brief-source-link" href="${escape(href)}" target="_blank" rel="noopener noreferrer">${escape(label)} ↗</a>`:`<span>${escape(label)}</span>`;}
 function renderBriefing(archive,asOf,language,items=[]){
  const t=i18n.dictionary(language).briefing,e=core.selectEdition(archive,asOf),date=news.shanghaiDay(asOf),text=v=>v[language==='en'?'en':'zh'];
  const radar=`<section id="brief-radar" class="brief-closing"><h2>${t.radar}</h2><button type="button" class="brief-radar-link" data-view="Latest">${t.backToLatest} ↗</button></section>`;
  if(!e)return `<section id="brief-opening" class="brief-reading" data-briefing-status="unpublished"><h1>${escape(t.title)} <span>｜${date}</span></h1><p class="brief-empty">${t.unpublished}</p>${radar}</section>`;
  const related=new Map([...items.map(i=>[i.id,{title:i18n.content(i,'title',language),url:i.sourceUrl}]),...e.sources.map(s=>[s.id,{title:s.title,url:s.url}])]);
  const plain=values=>values.map(p=>`<p>${escape(text(p.text))}</p>`).join('');
  function storyBody(story){
   const seen=new Set();
   function explain(value){let output=value;for(const k of story.keywords){const term=text(k.term);if(!/^[A-Z][A-Za-z0-9]{1,}$/.test(term)||seen.has(term))continue;const pattern=new RegExp('\\b'+term+'\\b');if(pattern.test(output)){output=output.replace(pattern,term+(language==='zh'?'（':' (')+text(k.explanation)+(language==='zh'?'）':')'));seen.add(term);}}return escape(output);}
   const paragraphs=v=>v.map(p=>`<p>${explain(text(p.text))}</p>`).join('');
   const section=(key,label,v)=>v?.length?`<section class="brief-story-section" data-briefing-section="${key}"><h4>${label}</h4>${paragraphs(v)}</section>`:'';
   return `${section('verifiedFacts',t.facts,story.verifiedFacts)}<section class="brief-story-sources" data-briefing-section="sources"><h4>${t.sources}</h4><div>${story.sources.map(s=>sourceLink(s,language)).join('')}</div><p>${core.corroborated(story)?t.confirmed:t.singleSource}</p></section>${section('plainExplanation',t.meaning,[story.plainExplanation])}${section('example',t.example,story.example?[story.example]:[])}${section('whyItMatters',t.matters,story.whyItMatters)}${section('longTermView',t.yearView,story.longTermView)}${section('opportunities',t.opportunities,story.opportunities)}${section('risks',t.risks,story.risks)}${story.crossAnalysis?`<aside class="brief-cross-analysis">${paragraphs(story.crossAnalysis)}</aside>`:''}<section class="brief-story-keywords" data-briefing-section="keywords"><h4>${t.keywords}</h4><ul>${story.keywords.map(k=>`<li><strong>${escape(text(k.term))}</strong> — ${escape(text(k.explanation))}</li>`).join('')}</ul></section>${story.relatedStoryIds.some(id=>related.has(id)&&core.sourceUrl(related.get(id).url))?`<section class="brief-story-related" data-briefing-section="relatedStoryIds"><h4>${t.related}</h4>${story.relatedStoryIds.map(id=>{const r=related.get(id);return r&&core.sourceUrl(r.url)?`<a class="brief-source-link" href="${escape(r.url)}" target="_blank" rel="noopener noreferrer">${escape(r.title)} ↗</a>`:'';}).join('')}</section>`:''}`;
  }
  return `<div class="brief-reading" data-briefing-status="published"><header class="brief-masthead"><h1>${escape(t.title)} <span>｜${e.date}</span></h1></header><section id="brief-opening" class="brief-opening"><h2>${t.opening}</h2><p>${e.executiveOpening.map(p=>escape(text(p.text))).join(' ')}</p></section><section id="brief-top-stories"><h2>${t.topStories}</h2>${core.sortStories(e.stories).map((story,index)=>`<article class="brief-story" data-story-id="${escape(story.id)}"><header><span class="brief-story-index">${String(index+1).padStart(2,'0')}｜</span><h3>${escape(text(story.title))}</h3></header>${storyBody(story)}</article>`).join('')}</section><section id="brief-watch" class="brief-closing"><h2>${t.watchNext}</h2><ol>${e.watchNext.map(p=>`<li>${escape(text(p.text))}</li>`).join('')}</ol></section><section id="brief-keyword" class="brief-closing"><h2>${t.keyword}</h2><h3>${escape(text(e.keyword.term))}</h3>${plain([e.keyword.explanation])}<h4>${t.whyNow}</h4>${plain([e.keyword.whyNow])}</section>${e.framework?`<aside class="brief-framework">${plain([e.framework])}</aside>`:''}${radar}</div>`;
 }
 function renderNavigation(archive,asOf,language){const t=i18n.dictionary(language).briefing;const sections=[['brief-opening',t.opening],...(core.selectEdition(archive,asOf)?[['brief-top-stories',t.topStories],['brief-watch',t.watchNext],['brief-keyword',t.keyword]]:[]),['brief-radar',t.radar]];return sections.map(([id,title],i)=>`<a href="#${id}"><span class="nav-index">0${i+1}</span>${title}</a>`).join('');}
 return {renderBriefing,renderNavigation,sourceLink};
});
