/* Long-form reading surface; no rule-template prose or model calls. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./core.cjs'),require('../news/i18n.cjs'),require('../news/core.cjs'));else root.FrontierBriefingRender=factory(root.FrontierBriefing,root.FrontierI18n,root.FrontierData);})(typeof globalThis!=='undefined'?globalThis:this,function(core,i18n,news){
 const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function renderBriefing(archive,asOf,language){
  const t=i18n.dictionary(language).briefing,edition=core.selectEdition(archive,asOf),date=news.shanghaiDay(asOf),text=value=>value[language==='en'?'en':'zh'];
  if(!edition)return `<section id="brief-opening" class="brief-reading" data-briefing-status="unpublished"><h1>AI &amp; Frontier Briefing <span>｜${date}</span></h1><p class="brief-empty">${t.unpublished}</p><button type="button" class="brief-radar-link" data-view="Latest">${t.backToLatest} ↗</button></section>`;
  const sourceIndex=new Map(edition.sources.map((source,index)=>[source.id,index+1]));
  const citations=p=>`<sup class="brief-citations">${p.evidenceIds.map(id=>`<a href="#brief-source-${sourceIndex.get(id)}" aria-label="${t.source} ${sourceIndex.get(id)}">[${sourceIndex.get(id)}]</a>`).join(' ')}</sup>`;
  const paragraphs=values=>values.map(p=>`<p>${escape(text(p.text))}${citations(p)}</p>`).join('');
  const sections=[['confirmedFacts',t.facts],['whyItMatters',t.matters],['yearView',t.yearView],['opportunities',t.opportunities],['risks',t.risks]];
  return `<div class="brief-reading" data-briefing-status="published"><header class="brief-masthead"><h1>AI &amp; Frontier Briefing <span>｜${edition.date}</span></h1><p class="brief-edition-note">${t.editionNote}</p></header><section id="brief-opening" class="brief-opening"><p>${edition.executiveOpening.map(p=>escape(text(p.text))+citations(p)).join(' ')}</p></section><section id="brief-top-stories"><h2>${t.topStories}</h2>${edition.stories.length<3?`<p class="brief-edition-note">${t.sparse}</p>`:''}${edition.stories.map((story,index)=>`<article class="brief-story" data-story-id="${escape(story.id)}"><header><span class="brief-story-index">0${index+1}</span><h3><a class="article-title-link" href="${escape(edition.sources.find(source=>source.id===story.newsIds[0]).sourceUrl)}" target="_blank" rel="noopener noreferrer">${escape(text(story.title))}</a></h3></header>${sections.map(([field,label])=>`<section class="brief-story-section" data-briefing-section="${field}"><h4>${label}</h4>${paragraphs(story[field])}</section>`).join('')}${story.crossAnalysis?`<aside class="brief-cross-analysis">${paragraphs(story.crossAnalysis)}</aside>`:''}</article>`).join('')}</section><section id="brief-watch" class="brief-closing"><h2>${t.watchNext}</h2><ol>${edition.watchNext.map(p=>`<li>${escape(text(p.text))}${citations(p)}</li>`).join('')}</ol></section><section id="brief-keyword" class="brief-closing"><h2>${t.keyword}</h2><h3>${escape(text(edition.keyword.term))}</h3>${paragraphs([edition.keyword.explanation])}</section>${edition.framework?`<aside class="brief-framework">${paragraphs([edition.framework])}</aside>`:''}<details class="brief-sources"><summary>${t.sources} · ${edition.sources.length}</summary><ol>${edition.sources.map((source,index)=>`<li id="brief-source-${index+1}"><a href="${escape(source.sourceUrl)}" target="_blank" rel="noopener noreferrer">${escape(source.title)} ↗</a><span>${escape(source.source)} · <time datetime="${escape(source.publishedAt)}">${news.formatDate(source.publishedAt)}</time></span></li>`).join('')}</ol></details></div>`;
 }
 function renderNavigation(archive,asOf,language){const t=i18n.dictionary(language).briefing;const sections=[['brief-opening',t.opening],...(core.selectEdition(archive,asOf)?[['brief-top-stories',t.topStories],['brief-watch',t.watchNext],['brief-keyword',t.keyword]]:[])];return sections.map(([id,title],index)=>`<a href="#${id}"><span class="nav-index">0${index+1}</span>${title}</a>`).join('');}
 return {renderBriefing,renderNavigation};
});
