/* UI copy and optional story-language selection. No fetching or translation. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.FrontierI18n=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
 'use strict';
 const dictionaries={
  zh:{briefing:{title:'AI & 前沿简报',unpublished:'今天的前沿简报尚未生成。',archive:'往期简报',backToLatest:'进入长期趋势',radar:'长期趋势',opening:'今日总览',topStories:'今日重点',keyTakeaway:'关键信息',coverage:'覆盖时间',facts:'已验证事实',sources:'原文来源',meaning:'这是什么意思',example:'举个例子',matters:'为什么重要',yearView:'3–10 年观察',opportunities:'机会',risks:'风险',keywords:'关键词',related:'相关事件',watchNext:'接下来值得关注',keyword:'今日关键词',whyNow:'为什么现在值得记住',source:'来源',navigation:'简报目录',editionNote:'先讲人话，再讲专业判断。',sourceTypes:{official:'官方',news:'新闻',research:'研究'},singleSource:'按原始来源核对，尚无独立来源确认。',confirmed:'一手来源与独立来源交叉核对。'},pageTitle:'AI Frontier — 个人前沿科技情报终端',description:'个人前沿科技情报终端，关注 AI、智能体、芯片、机器人与加密技术的变化及其长期影响。',
   personal:'个人情报',edition:'本地快照',skip:'跳转到内容',domains:'观察领域 / 05',navigation:'栏目导航',sidebar:'独立观察。<br>持续形成判断。',eyebrow:'个人前沿科技情报终端',tagline:'追踪重要变化。理解它们为何重要。',viewLabel:'浏览视角',
   views:{Today:'今日',Latest:'最新', 'Long-term':'长期趋势','Daily Briefing':'每日简报'},signals:'重要信号',priority:'优先关注',signalCaption:(view,n,demo)=>(view==='Today'||view==='Daily Briefing'?'当天':view==='Long-term'?'长期':'最近')+'最值得关注的 '+n+' 件事'+(demo?' · 示例精选':''),
   meaning:'这是什么意思',keywords:'关键词',trendNote:'只展示已有中文解释的长期观察。尚未完成中文编辑的候选暂不展示。',happened:'发生了什么',matters:'为什么重要',impact:'长期影响',implication:'影响分析',readOriginal:'查看原文',related:n=>'主题关联 · '+n,relatedNote:'共享主题线索，供交叉阅读。',showAll:'查看全部',collapse:'收起',entries:n=>n+' 条',emptyContent:'当前筛选暂无内容。',emptySignals:'当前筛选暂无信号。',radarUpdated:'新闻雷达更新',briefingEdition:date=>'本期简报：'+date,briefingPending:date=>'今日简报尚未发布，当前显示上一期：'+date,updated:'最后更新',noUpdate:'尚无真实更新 · 本地示例',beijing:'北京时间',briefingCount:n=>' · 每日简报：'+n+' 条当天精选'+(n<5?'（当天合格内容不足 5 条，不补旧闻）':''),
   fieldNotes:'详细浏览',fieldCount:n=>'05 领域 · '+n+' 条精选',sectionCount:(featured,total)=>'精选 '+String(featured).padStart(2,'0')+' / 共 '+String(total).padStart(2,'0'),footer:'独立观察，持续思考。',demoFooter:'本地示例内容与日期 · 非实时新闻',realFooter:'本地新闻快照',
   language:'语言',languageZh:'中文',theme:'主题',auto:'自动',system:'跟随系统',light:'浅色',dark:'深色',badge:'中',
   categories:{ai:['AI','理解模型能力的边界与新的应用机会。'],agents:['智能体','关注智能体如何可靠地完成真实任务。'],chips:['GPU 与芯片','从算力效率看 AI 基础设施的演进。'],robotics:['机器人','追踪智能从数字世界走向物理世界。'],crypto:['加密与支付','观察可信计算与价值流转的新基础设施。']},domainsShort:{ai:'AI',agents:'智能体',chips:'芯片',robotics:'机器人',crypto:'加密与支付'}},
  en:{briefing:{title:'AI & Frontier Briefing',unpublished:'Today’s Frontier Briefing has not been generated.',archive:'Past Briefings',backToLatest:'Explore long-term trends',radar:'Long-term trends',opening:'Today at a glance',topStories:'Today’s highlights',keyTakeaway:'Key takeaway',coverage:'Coverage',facts:'Verified facts',sources:'Original sources',meaning:'What this means',example:'A concrete example',matters:'Why it matters',yearView:'3–10 year view',opportunities:'Opportunities',risks:'Risks',keywords:'Keywords',related:'Related events',watchNext:'What to watch next',keyword:'Today’s keyword',whyNow:'Why remember it now',source:'Source',navigation:'Briefing contents',editionNote:'Plain language first. Deeper judgment next.',sourceTypes:{official:'Official',news:'News',research:'Research'},singleSource:'Checked against the original source; not independently confirmed.',confirmed:'Cross-checked with primary and independent sources.'},pageTitle:'AI Frontier — Personal Frontier Intelligence',description:'Personal intelligence on AI, agents, chips, robotics and crypto: track important developments and their long-term implications.',
   personal:'PERSONAL INTELLIGENCE',edition:'LOCAL EDITION',skip:'Skip to content',domains:'OBSERVATION AREAS / 05',navigation:'Categories',sidebar:'Independent observation.<br>Develop your perspective.',eyebrow:'PERSONAL FRONTIER INTELLIGENCE',tagline:'Track what matters. Understand why it matters.',viewLabel:'Browse perspectives',
   views:{Today:'Today',Latest:'Latest','Long-term':'Long-term','Daily Briefing':'Daily Briefing'},signals:'Top Signals',priority:'PRIORITY',signalCaption:(view,n,demo)=>(view==='Today'||view==='Daily Briefing'?"Today's":view==='Long-term'?'Long-term':'Latest')+' '+n+' signals to watch'+(demo?' · Sample selection':''),
   meaning:'What this means',keywords:'Keywords',trendNote:'Reviewed developments with a 3–10 year horizon. Candidates awaiting editorial explanation stay out of this view.',happened:'What happened',matters:'Why it matters',impact:'Long-term impact',implication:'IMPLICATION',readOriginal:'Read original',related:n=>'Related topics · '+n,relatedNote:'Shared themes for cross-reading.',showAll:'View all',collapse:'Show less',entries:n=>n+' stories',emptyContent:'No stories in this view.',emptySignals:'No signals in this view.',radarUpdated:'News Radar updated',briefingEdition:date=>'Briefing edition: '+date,briefingPending:date=>'Today’s briefing has not been published. Showing the latest edition: '+date,updated:'Last updated',noUpdate:'No live update yet · Local sample',beijing:'Beijing time',briefingCount:n=>' · Daily Briefing: '+n+' stories today'+(n<5?' (fewer than 5 eligible today; no older stories added)':''),
   fieldNotes:'FIELD NOTES',fieldCount:n=>'05 areas · '+n+' featured',sectionCount:(featured,total)=>'Featured '+String(featured).padStart(2,'0')+' / Total '+String(total).padStart(2,'0'),footer:'Independent observation. Keep thinking.',demoFooter:'Local sample content and dates · Not live news',realFooter:'Local news snapshot',
   language:'Language',languageZh:'Chinese',theme:'Theme',auto:'Auto',system:'System',light:'Light',dark:'Dark',badge:'EN',
   categories:{ai:['AI','Explore model capabilities and emerging applications.'],agents:['Agents','Follow agents that reliably complete real tasks.'],chips:['GPU & Chips','Track compute efficiency and the evolution of AI infrastructure.'],robotics:['Robotics','Follow intelligence moving from digital to physical worlds.'],crypto:['Crypto','Explore infrastructure for trust and value transfer.']},domainsShort:{ai:'AI',agents:'Agents',chips:'Chips',robotics:'Robotics',crypto:'Crypto'}}
 };
 function dictionary(language){return dictionaries[language==='en'?'en':'zh'];}
 function resolveLanguage(preference,navigator){
  if(preference==='zh'||preference==='en')return preference;
  const preferred=navigator?.languages?.[0]||navigator?.language||'en';return /^zh(?:-|$)/i.test(preferred)?'zh':'en';
 }
 function content(object,field,language){const localized=object?.[field+(language==='en'?'En':'Zh')];return typeof localized==='string'&&localized.trim()?localized:typeof object?.[field]==='string'?object[field]:'';}
 function signalContent(item,field,briefField,language){
  const suffix=language==='en'?'En':'Zh';
  for(const value of [item.signalBrief?.[briefField+suffix],item[field+suffix],item.signalBrief?.[briefField],content(item,field,language)])if(typeof value==='string'&&value.trim())return value;
  return '';
 }
 function formatUpdated(value,language){
  const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value)).map(p=>[p.type,p.value]));
  return `${p.year}-${p.month}-${p.day} ${p.hour}:${p.minute} ${dictionary(language).beijing}（${new Date(value).toISOString().slice(0,16).replace('T',' ')} UTC）`.replace('（',language==='en'?' (':'（').replace('）',language==='en'?')':'）');
 }
 return {dictionary,resolveLanguage,content,signalContent,formatUpdated};
});

