/* UI copy and optional story-language selection. No fetching or translation. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.FrontierI18n=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
 'use strict';
 const dictionaries={
  zh:{health:{categories:{ai:'AI',agents:'智能体',chips:'GPU 与芯片',robotics:'机器人',crypto:'加密与稳定币'},entryUpdated:'来源条目更新时间',title:'来源健康',back:'返回 Frontier',explanation:'逐源记录公开 Feed 的可用性和更新情况；单个来源异常不影响其他来源。',checked:'最后检查',enabled:'启用',good:'正常',warning:'警告',failed:'失败',blocked:'网络受阻',success:'最近成功抓取',published:'最近原始发布',failures:'连续失败',entries:'最近有效条目',diagnostic:'技术诊断',feed:'打开原始 Feed',never:'尚无记录',recovered:'已恢复',pending:'尚未执行来源检查。',overdue:'超过 9 小时未记录检查，请查看 GitHub Actions 是否仍在刷新。',cadence:'每 3 小时检查一次。来源失败会持续标记并在下次刷新重试；不自动永久禁用。',language:'语言',theme:'主题',states:{healthy:'正常','no-matches':'正常 · 暂无相关内容',empty:'可访问 · 暂无条目',degraded:'部分条目异常',stale:'发布超过预期周期',error:'抓取或解析失败',blocked:'检查网络受阻',pending:'待检查',disabled:'未启用'}},sourceHealth:'来源健康',sourceProblems:n=>'异常 '+n+' 项',briefing:{title:'AI & 前沿简报',unpublished:'今天的前沿简报尚未生成。',backToLatest:'进入新闻雷达',radar:'新闻雷达',opening:'今日总览',topStories:'今日重点',facts:'已验证事实',sources:'原文来源',meaning:'这是什么意思',example:'举个例子',matters:'为什么重要',yearView:'3–10 年观察',opportunities:'机会',risks:'风险',keywords:'关键词',related:'相关事件',watchNext:'接下来值得关注',keyword:'今日关键词',whyNow:'为什么现在值得记住',source:'来源',navigation:'简报目录',editionNote:'先讲人话，再讲专业判断。',sourceTypes:{official:'官方',news:'新闻',research:'研究'},singleSource:'按原始来源核对，尚无独立来源确认。',confirmed:'一手来源与独立来源交叉核对。'},pageTitle:'AI Frontier — 个人前沿科技情报终端',description:'个人前沿科技情报终端，关注 AI、智能体、芯片、机器人与加密技术的变化及其长期影响。',
   personal:'个人情报',edition:'本地快照',skip:'跳转到内容',domains:'观察领域 / 05',navigation:'栏目导航',sidebar:'独立观察。<br>持续形成判断。',eyebrow:'个人前沿科技情报终端',tagline:'追踪重要变化。理解它们为何重要。',viewLabel:'浏览视角',
   views:{Today:'今日',Latest:'最新', 'Long-term':'长期趋势','Daily Briefing':'每日简报'},signals:'重要信号',priority:'优先关注',signalCaption:(view,n,demo)=>(view==='Today'||view==='Daily Briefing'?'当天':view==='Long-term'?'长期':'最近')+'最值得关注的 '+n+' 件事'+(demo?' · 示例精选':''),
   happened:'发生了什么',matters:'为什么重要',impact:'长期影响',implication:'影响分析',readOriginal:'查看原文',related:n=>'主题关联 · '+n,relatedNote:'共享主题线索，供交叉阅读。',showAll:'查看全部',collapse:'收起',entries:n=>n+' 条',emptyContent:'当前筛选暂无内容。',emptySignals:'当前筛选暂无信号。',updated:'最后更新',noUpdate:'尚无真实更新 · 本地示例',beijing:'北京时间',briefingCount:n=>' · 每日简报：'+n+' 条当天精选'+(n<5?'（当天合格内容不足 5 条，不补旧闻）':''),
   fieldNotes:'详细浏览',fieldCount:n=>'05 领域 · '+n+' 条精选',sectionCount:(featured,total)=>'精选 '+String(featured).padStart(2,'0')+' / 共 '+String(total).padStart(2,'0'),footer:'独立观察，持续思考。',demoFooter:'本地示例内容与日期 · 非实时新闻',realFooter:'本地新闻快照',
   language:'语言',languageZh:'中文',theme:'主题',auto:'自动',system:'跟随系统',light:'浅色',dark:'深色',badge:'中',
   categories:{ai:['AI','理解模型能力的边界与新的应用机会。'],agents:['Agents','关注智能体如何可靠地完成真实任务。'],chips:['GPU & Chips','从算力效率看 AI 基础设施的演进。'],robotics:['Robotics','追踪智能从数字世界走向物理世界。'],crypto:['Crypto','观察可信计算与价值流转的新基础设施。']},domainsShort:{ai:'AI',agents:'Agents',chips:'Chips',robotics:'Robotics',crypto:'Crypto'}},
  en:{health:{categories:{ai:'AI',agents:'Agents',chips:'GPU & Chips',robotics:'Robotics',crypto:'Crypto & Stablecoins'},entryUpdated:'Source entry updated',title:'Source health',back:'Back to Frontier',explanation:'Publisher-owned feed availability and freshness. One source failure does not stop other feeds.',checked:'Last check',enabled:'Enabled',good:'Healthy',warning:'Warnings',failed:'Failed',blocked:'Network blocked',success:'Last successful fetch',published:'Latest original publication',failures:'Consecutive failures',entries:'Last valid entries',diagnostic:'Technical diagnosis',feed:'Open original feed',never:'No record yet',recovered:'Recovered',pending:'No source checks have run yet.',overdue:'No recorded check for over 9 hours. Check the refresh workflow in GitHub Actions.',cadence:'Checked every 3 hours. Failed feeds stay marked and retry on the next refresh; they are not permanently disabled.',language:'Language',theme:'Theme',states:{healthy:'Healthy','no-matches':'Healthy · No matching topics',empty:'Reachable · Empty feed',degraded:'Some entries rejected',stale:'Publication exceeds expected cadence',error:'Fetch or parser failure',blocked:'Check network blocked',pending:'Pending check',disabled:'Not enabled'}},sourceHealth:'Source health',sourceProblems:n=>n+' source issues',briefing:{title:'AI & Frontier Briefing',unpublished:'Today’s Frontier Briefing has not been generated.',backToLatest:'Open News Radar',radar:'News Radar',opening:'Today at a glance',topStories:'Today’s highlights',facts:'Verified facts',sources:'Original sources',meaning:'What this means',example:'A concrete example',matters:'Why it matters',yearView:'3–10 year view',opportunities:'Opportunities',risks:'Risks',keywords:'Keywords',related:'Related events',watchNext:'What to watch next',keyword:'Today’s keyword',whyNow:'Why remember it now',source:'Source',navigation:'Briefing contents',editionNote:'Plain language first. Deeper judgment next.',sourceTypes:{official:'Official',news:'News',research:'Research'},singleSource:'Checked against the original source; not independently confirmed.',confirmed:'Cross-checked with primary and independent sources.'},pageTitle:'AI Frontier — Personal Frontier Intelligence',description:'Personal intelligence on AI, agents, chips, robotics and crypto: track important developments and their long-term implications.',
   personal:'PERSONAL INTELLIGENCE',edition:'LOCAL EDITION',skip:'Skip to content',domains:'OBSERVATION AREAS / 05',navigation:'Categories',sidebar:'Independent observation.<br>Develop your perspective.',eyebrow:'PERSONAL FRONTIER INTELLIGENCE',tagline:'Track what matters. Understand why it matters.',viewLabel:'Browse perspectives',
   views:{Today:'Today',Latest:'Latest','Long-term':'Long-term','Daily Briefing':'Daily Briefing'},signals:'Top Signals',priority:'PRIORITY',signalCaption:(view,n,demo)=>(view==='Today'||view==='Daily Briefing'?"Today's":view==='Long-term'?'Long-term':'Latest')+' '+n+' signals to watch'+(demo?' · Sample selection':''),
   happened:'What happened',matters:'Why it matters',impact:'Long-term impact',implication:'IMPLICATION',readOriginal:'Read original',related:n=>'Related topics · '+n,relatedNote:'Shared themes for cross-reading.',showAll:'View all',collapse:'Show less',entries:n=>n+' stories',emptyContent:'No stories in this view.',emptySignals:'No signals in this view.',updated:'Last updated',noUpdate:'No live update yet · Local sample',beijing:'Beijing time',briefingCount:n=>' · Daily Briefing: '+n+' stories today'+(n<5?' (fewer than 5 eligible today; no older stories added)':''),
   fieldNotes:'FIELD NOTES',fieldCount:n=>'05 areas · '+n+' featured',sectionCount:(featured,total)=>'Featured '+String(featured).padStart(2,'0')+' / Total '+String(total).padStart(2,'0'),footer:'Independent observation. Keep thinking.',demoFooter:'Local sample content and dates · Not live news',realFooter:'Local news snapshot',
   language:'Language',languageZh:'Chinese',theme:'Theme',auto:'Auto',system:'System',light:'Light',dark:'Dark',badge:'EN',
   categories:{ai:['AI','Explore model capabilities and emerging applications.'],agents:['Agents','Follow agents that reliably complete real tasks.'],chips:['GPU & Chips','Track compute efficiency and the evolution of AI infrastructure.'],robotics:['Robotics','Follow intelligence moving from digital to physical worlds.'],crypto:['Crypto','Explore infrastructure for trust and value transfer.']},domainsShort:{ai:'AI',agents:'Agents',chips:'Chips',robotics:'Robotics',crypto:'Crypto'}}
 };
 function dictionary(language){return dictionaries[language==='en'?'en':'zh'];}
 function resolveLanguage(preference,navigator){
  if(preference==='zh'||preference==='en')return preference;
  const preferred=navigator?.languages?.[0]||navigator?.language||'en';return /^zh(?:-|$)/i.test(preferred)?'zh':'en';
 }
 function content(object,field,language){const localized=object?.[field+(language==='en'?'En':'Zh')];return typeof localized==='string'&&localized.trim()?localized:typeof object?.[field]==='string'?object[field]:'';}
 function signalContent(item,field,briefField,language){
  const suffix=language==='en'?'En':'Zh';
  for(const value of [item.signalBrief?.[briefField+suffix],item[field+suffix],item.signalBrief?.[briefField],content(item,field,language)])if(typeof value==='string'&&value.trim())return value;
  return '';
 }
 function formatUpdated(value,language){
  const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value)).map(p=>[p.type,p.value]));
  return `${p.year}-${p.month}-${p.day} ${p.hour}:${p.minute} ${dictionary(language).beijing}（${new Date(value).toISOString().slice(0,16).replace('T',' ')} UTC）`.replace('（',language==='en'?' (':'（').replace('）',language==='en'?')':'）');
 }
 return {dictionary,resolveLanguage,content,signalContent,formatUpdated};
});
