/* Presentation only. Receives a view model; performs no fetching, filtering or ranking. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./core.cjs'),require('./i18n.cjs'),require('../briefing/render.cjs'));else root.FrontierRender=factory(root.FrontierData,root.FrontierI18n,root.FrontierBriefingRender);})(typeof globalThis!=='undefined'?globalThis:this,function(core,i18n,briefing){
 const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function articleUrl(item,isDemo){
  if(isDemo||typeof item.sourceUrl!=='string')return null;
  const value=item.sourceUrl.trim();if(!/^https?:\/\//i.test(value))return null;
  try{const url=new URL(value);if(!url.hostname||url.username||url.password)return null;return value;}catch{return null;}
 }
 function titleLink(item,title,ctx){const href=articleUrl(item,ctx.isDemo);return href?`<a class="article-title-link" href="${escape(href)}" target="_blank" rel="noopener noreferrer">${escape(title)}</a>`:escape(title);}
 function sourceLink(item,ctx){const href=articleUrl(item,ctx.isDemo);return href?`<a class="article-source-link" href="${escape(href)}" target="_blank" rel="noopener noreferrer">${escape(i18n.content(item,'source',ctx.language))} · ${ctx.t.readOriginal} ↗</a>`:'';}
 function renderRelated(item,ctx){
  const links=(item.ruleAnalysis?.relatedNews||[]).map(r=>ctx.byId.get(r.id)).filter(other=>other&&articleUrl(other,ctx.isDemo)).slice(0,3);
  return links.length?`<details class="topic-relations"><summary>${ctx.t.related(links.length)}</summary><p>${ctx.t.relatedNote}</p><ul>${links.map(other=>`<li><a href="${escape(articleUrl(other,ctx.isDemo))}" target="_blank" rel="noopener noreferrer">${escape(i18n.content(other,'title',ctx.language))} ↗</a><time>${core.formatDate(other.publishedAt)}</time></li>`).join('')}</ul></details>`:'';
 }
 function renderCard(item,ctx){
  const localizedTags=item[ctx.language==='en'?'tagsEn':'tagsZh'];const tags=Array.isArray(localizedTags)&&localizedTags.every(tag=>typeof tag==='string')?localizedTags:item.tags;
  return `<article class="card" data-item-id="${escape(item.id)}"><div class="card-meta"><span class="tag">${escape(tags.join(' · '))}</span><time datetime="${escape(item.publishedAt)}">${core.formatDate(item.publishedAt)}</time><span>${escape(i18n.content(item,'source',ctx.language))}</span></div><h3>${titleLink(item,i18n.content(item,'title',ctx.language),ctx)}</h3><p class="summary">${escape(i18n.content(item,'summary',ctx.language))}</p><div class="importance"><span class="importance-label">${ctx.t.matters} <span> / ${ctx.t.implication}</span></span><p>${escape(i18n.content(item,'whyItMatters',ctx.language))}</p></div>${sourceLink(item,ctx)}${renderRelated(item,ctx)}</article>`;
 }
 function renderSection(category,index,ctx){
  const total=category.entries.length,featured=Math.min(2,total),copy=ctx.t.categories[category.id];
  return `<section id="${category.id}" class="category category-${category.id}" aria-labelledby="${category.id}-title"><header class="section-heading"><span class="section-index">0${index+1}</span><div><h2 id="${category.id}-title">${escape(copy?.[0]||category.title)}</h2><p>${escape(copy?.[1]||category.subtitle)}</p></div><span class="section-count">${ctx.t.sectionCount(featured,total)}</span></header>${total?`<div class="cards">${category.entries.slice(0,2).map(e=>renderCard(e,ctx)).join('')}</div>`:`<p class="summary">${ctx.t.emptyContent}</p>`}${total>2?`<details class="more-entries"><summary><span class="show-more">${ctx.t.showAll} <span>${ctx.t.entries(total)}</span></span><span class="show-less">${ctx.t.collapse}</span></summary><div class="cards">${category.entries.slice(2).map(e=>renderCard(e,ctx)).join('')}</div></details>`:''}</section>`;
 }
 function renderSignals(vm,ctx){
  return `<section class="top-signals" aria-labelledby="top-signals-title"><header class="signals-heading"><div><h2 id="top-signals-title">${ctx.t.signals}</h2><p>${ctx.t.signalCaption(vm.view,vm.signals.length,vm.isDemo)}</p></div><span class="signals-edition">${String(vm.signals.length).padStart(2,'0')} / ${ctx.t.priority}</span></header><div class="signals-grid">${vm.signals.map(item=>`<article class="signal" data-item-id="${escape(item.id)}"><div class="signal-title"><h3>${titleLink(item,i18n.signalContent(item,'title','title',ctx.language),ctx)}</h3><span class="signal-domain">${ctx.t.domainsShort[item.category]}</span></div><dl><div><dt>${ctx.t.happened}</dt><dd>${escape(i18n.signalContent(item,'summary','happened',ctx.language))}</dd></div><div><dt>${ctx.t.matters}</dt><dd>${escape(i18n.signalContent(item,'whyItMatters','matters',ctx.language))}</dd></div><div class="signal-impact"><dt>${ctx.t.impact}</dt><dd>${escape(i18n.signalContent(item,'longTermImpact','impact',ctx.language))}</dd></div></dl>${sourceLink(item,ctx)}</article>`).join('')||`<p class="summary">${ctx.t.emptySignals}</p>`}</div></section>`;
 }
 function controls(options,t){
  const button=(attribute,value,label,selected)=>`<button type="button" ${attribute}="${value}" aria-pressed="${selected===value}">${label}</button>`;
  return `<div class="preferences"><details class="preference-menu" data-preference="language"><summary aria-label="${t.language}">${t.badge}</summary><div class="preference-options" role="group" aria-label="${t.language}">${button('data-language','auto',t.auto,options.languagePreference||'auto')}${button('data-language','zh',t.languageZh,options.languagePreference||'auto')}${button('data-language','en','English',options.languagePreference||'auto')}</div></details><details class="preference-menu" data-preference="theme"><summary aria-label="${t.theme}">${options.theme==='dark'?'◐':'☀'}</summary><div class="preference-options" role="group" aria-label="${t.theme}">${button('data-theme','system',t.system,options.themePreference||'system')}${button('data-theme','light',t.light,options.themePreference||'system')}${button('data-theme','dark',t.dark,options.themePreference||'system')}</div></details></div>`;
 }
 function renderDashboard(vm,options={}){
  const language=options.language==='en'?'en':'zh',t=i18n.dictionary(language),ctx={language,t,isDemo:vm.isDemo,byId:new Map((vm.relatedItems||vm.items).map(item=>[item.id,item]))};
  const isBriefing=vm.view==='Daily Briefing';
  const editionNote='';
  const nav=isBriefing?briefing.renderNavigation(options.briefing,vm.asOf,language,vm.relatedItems):vm.categories.map((c,i)=>`<a href="#${c.id}"><span class="nav-index">0${i+1}</span>${escape(t.categories[c.id]?.[0]||c.title)}</a>`).join('');
  const note=`${t.updated}：${vm.isDemo?t.noUpdate:i18n.formatUpdated(vm.snapshotAt,language)}`;
  return `<a class="skip-link" href="#main">${t.skip}</a><header class="topbar"><a class="brand" href="#">FRONTIER <span>/ ${t.personal}</span></a><div class="topbar-tools"><span class="edition">${t.edition}</span></div></header><div class="shell"><aside class="sidebar"><div class="nav-label">${isBriefing?t.briefing.navigation:t.domains}</div><nav aria-label="${isBriefing?t.briefing.navigation:t.navigation}">${nav}</nav><p class="sidebar-note">${t.sidebar}</p></aside><main id="main">${isBriefing?'':`<div class="intro"><div class="eyebrow">${t.eyebrow}</div><h1>AI Frontier</h1><p>${t.tagline}</p></div>`}<div class="brief-toolbar"><div class="view-filters" role="group" aria-label="${t.viewLabel}">${core.views.map(label=>`<button type="button" data-view="${label}" aria-pressed="${vm.view===label}">${t.views[label]}</button>`).join('')}</div>${controls(options,t)}</div><p class="demo-note">${note}${editionNote}</p>${isBriefing?briefing.renderBriefing(options.briefing,vm.asOf,language,vm.relatedItems):`${renderSignals(vm,ctx)}<div class="feed-title"><span>${t.fieldNotes}</span><span>${t.fieldCount(vm.featuredCount)}</span></div>${vm.categories.map((c,i)=>renderSection(c,i,ctx)).join('')}`}<footer><span>FRONTIER / ${t.footer}</span><span>${vm.isDemo?t.demoFooter:t.realFooter}</span></footer></main></div>`;
 }
 return {renderDashboard};
});
